
module.exports = {
	"ActionTypes":{
    	"GET_DEFINITION":"GET_DEFINITION",
    	"RECEIVE_DEFINITION":"RECEIVE_DEFINITION",
    	"GET_SCHEMA_RECORDS": "GET_SCHEMA_RECORDS",
    	"RECEIVE_ALL_SCHEMAS":"RECEIVE_ALL_SCHEMAS",
    	"RECEIVE_SCHEMA_RECORDS":"RECEIVE_SCHEMA_RECORDS",
    	"GET_SCHEMAS":"GET_SCHEMAS",
    	"RECEIVE_SCHEMAS":"RECEIVE_SCHEMAS",
    	"GET_USER_DETAILS":"GET_USER_DETAILS",
    	"RECEIVE_USER_DETAILS":"RECEIVE_USER_DETAILS",
    	"GET_RELATED":"GET_RELATED",
    	"RECEIVE_RELATED":"RECEIVE_RELATED",
        "GET_SCHEMA_RECORD":"GET_SCHEMA_RECORD",
        "RECEIVE_SCHEMA_RECORD":"RECEIVE_SCHEMA_RECORD",
        "GET_RELATION_RECORDS":"GET_RELATION_RECORDS",
        "RECEIVE_RELATION_RECORDS":"RECEIVE_RELATION_RECORDS",
        "CREATE_RECORD":"CREATE_RECORD",
        "GET_NAVIGATION_LINKS":"GET_NAVIGATION_LINKS",
        "RECEIVE_NAVIGATION_LINKS":"RECEIVE_NAVIGATION_LINKS",
        "UPDATE_RECORD":"UPDATE_RECORD",
        "RECEIVE_RELATED_RECORDS":"RECEIVE_RELATED_RECORDS",
        "RECEIVE_RELATED_COUNT":"RECEIVE_RELATED_COUNT"
	}
};